# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('미국', '미국'), ('은지', '은지'), ('졸업식', '졸업식')], default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='photo', max_length=100),
        ),
    ]
