# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobook', '0004_auto_20170514_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='blog/%Y/%M/%D'),
        ),
    ]
