# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobook', '0005_auto_20170514_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('글로벌 챌린지', '글로벌 챌린지'), ('은지', '은지'), ('바르셀로나mwc', '바르셀로나mwc'), ('인도네시아 코이카 탐방', '인도네시아 코이카 탐방')], default=False, max_length=100),
        ),
    ]
